version: '3'
services:
  api:
    build: ./api
    ports:
      - '8000:8080'
    environment:
      - ConnectionStrings__DefaultConnection=Host=db;Database=postgres;Username=postgres;Password=Your_password123;

  frontend:
    build: ./front-end
    ports:
      - '1234:1234'
    depends_on:
      - api

  db:
    image: postgres:14
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=Your_password123
      - POSTGRES_DB=postgres
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: